# coding:utf-8
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_001 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_002 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_003 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_004 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_005 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_006 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_007 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_008 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_009 import *
from src.testcase.case.GNAPP_PERSONAL_SETTINGS.GNAPP_PERSONAL_SETTINGS_010 import *
