# coding=utf-8
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_001 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_002 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_003 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_004 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_005 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_006 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_007 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_008 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_009 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_010 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_011 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_012 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_013 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_014 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_015 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_016 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_017 import *
from src.testcase.case.GNAPP_REGISTER.GNAPP_REGISTER_018 import *
