# coding=utf-8
from src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_001 import *
from src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_002 import *
from src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_003 import *
from src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_004 import *
from src.testcase.case.GNAPP_MESSAGE_CLASSIFY.GNAPP_MESSAGE_CLASSIFY_005 import *
