# coding:utf-8
# 由Conf.py生成
from src.testcase.page.AppPageElement import *

account_setting_page = MainPageWidget().account_setting_page()
add_device_failed_page = MainPageWidget().add_device_failed_page()
app_help_page = MainPageWidget().app_help_page()
change_nickname_page = MainPageWidget().change_nickname_page()
change_pwd_page = MainPageWidget().change_pwd_page()
device_add_scan_page = MainPageWidget().device_add_scan_page()
device_control_page = MainPageWidget().device_control_page()
device_page = MainPageWidget().device_page()
feedback_page = MainPageWidget().feedback_page()
find_password_page = MainPageWidget().find_password_page()
gender_page = MainPageWidget().gender_page()
home_message_page = MainPageWidget().home_message_page()
login_page = MainPageWidget().login_page()
message_classify_page = MainPageWidget().message_classify_page()
new_password_page = MainPageWidget().new_password_page()
personal_settings_page = MainPageWidget().personal_settings_page()
prepare_set_network_page = MainPageWidget().prepare_set_network_page()
protocol_page = MainPageWidget().protocol_page()
register_page = MainPageWidget().register_page()
scan_with_subscribe_page = MainPageWidget().scan_with_subscribe_page()
set_network_page = MainPageWidget().set_network_page()
upgrade_page = MainPageWidget().upgrade_page()
view_pager_page = MainPageWidget().view_pager_page()

loading_popup = PopupWidget().loading_popup()
login_popup = PopupWidget().login_popup()
logout_popup = PopupWidget().logout_popup()
terminate_add_device_popup = PopupWidget().terminate_add_device_popup()
update_popup = PopupWidget().update_popup()
